name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18.14.0
          cache: "yarn"
      - name: Install Yarn v3
        run: |
          corepack enable
          corepack prepare yarn@3.4.1 --activate
      - name: Install dependencies
        run: yarn
      - name: Build typedocs
        run: |
          cd packages/react-sdk
          yarn typedoc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/react-sdk/docs
